import { Inter } from "next/font/google";
import "./globals.scss";
import TopBar from "./components/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nick's Portfolio Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
   
      <body className={inter.className}>
        <TopBar />
        {children}
      </body>
    </html>
  );
}
